version: '3.2'

networks:
  matecat-network:
    driver: bridge

services:
  filters:
    build: ./MateCatFilters/
    container_name: docker_matecat_filter
    ports:
      - 8732:8732
    networks:
       - matecat-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
       - matecat-network

  amq:
    build: ./AMQ/
    container_name: docker_amq
    ports:
      - 61613:61613
      - 8161:8161
    networks:
      matecat-network:
        aliases:
          - amq
  mysql:
    container_name: docker_mysql
    image: mysql/mysql-server:5.7
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: matecat
        MYSQL_USER: matecat
        MYSQL_PASSWORD: matecat
    networks:
      matecat-network:
        aliases:
          - mysql

  matecat:
    build: ./MateCatApache/
    container_name: docker_matecat
    ports:
      - 80:80
      - 443:443
      - 7788:7788
    networks:
       - matecat-network
    links:
      - mysql
      - redis
      - amq
      - filters
